<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<None Include="LICENSE.txt" Pack="true" PackagePath=""/>
	</ItemGroup>

  <PropertyGroup>
	<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	<PackageId>SharpHdl.Core</PackageId>
	<Version>0.2.0</Version>
	<Authors>araiguma</Authors>
	<Description>C# DSL for describing synchronous hardware (AST and Module API).</Description>
	<PackageProjectUrl>https://github.com/yukari6559/CsharpHdl</PackageProjectUrl>
	<RepositoryUrl>https://github.com/yukari6559/CsharpHdl</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageTags>hdl;verilog;csharp;fpga;rtl</PackageTags>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
