<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SharpHdl.Core\SharpHdl.Core.csproj" />
	<None Include="LICENSE.txt" Pack="true" PackagePath=""/>
  </ItemGroup>

  <PropertyGroup>
	<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  	<PackageId>SharpHdl.Emit</PackageId>
	<Version>0.1.0</Version>
	<Authors>araiguma</Authors>
	<Description>Verilog emitter for SharpHdl.Core modules.</Description>
	<PackageProjectUrl>https://github.com/yukari6559/CsharpHdl</PackageProjectUrl>
	<RepositoryUrl>https://github.com/yukari6559/CsharpHdl</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageTags>hdl;verilog;csharp;fpga;rtl;emitter</PackageTags>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
