using System.Text;
using SharpHdl.Core.Model;

namespace SharpHdl.Emit;

/// <summary>
/// Verilog emitter の入口プレースホルダ。実装は docs/verilog-emit-spec.md に従う。
/// </summary>
public static class VerilogEmitter
{
    public static string EmitPlaceholder(string moduleName) =>
        $"// Generated by CsharpHdl (stub)\nmodule {moduleName};\nendmodule\n";

	public static string Emitter(Module top, string topName)
	{
		List<InstanceStmt> instanceStmts = new();

		return EmitOneModule(top, topName, instanceStmts, true);
	}

	public static string emitExpr(Expr expr)
	{
		
		if(expr is Signal)
		{
			Signal signal = (Signal)expr;
			return signal.Name;
		}
		else if(expr is OpExpr)
		{
			OpExpr opExpr = (OpExpr)expr;
			return emitExpr(opExpr.Left) + " " + opExpr.Op.ToCustomString() + " " + emitExpr(opExpr.Right);
		}
		else if(expr is SliceExpr sliceExpr)
		{
			return emitExpr(sliceExpr.Expr) + $"[{sliceExpr.MSB}:{sliceExpr.LSB}]";
		}
		else if(expr is ConcatExpr concatExpr)
		{
			string s = "{";
			for(int i = 0; i < concatExpr.Exprs.Count(); i++)
			{
				if(i == concatExpr.Exprs.Count() - 1)
					s += $"{emitExpr(concatExpr.Exprs[i])}";
				else
					s += $"{emitExpr(concatExpr.Exprs[i])}, ";
			}
			s += "}";
			return s;
		}
		else if(expr is SignExtendExpr signExtendExpr)
		{
			if(signExtendExpr.GetWidth() - signExtendExpr.Expr.GetWidth() == 0)
				return emitExpr(signExtendExpr.Expr);
			else
			{
				string s = "{{" + $"{signExtendExpr.GetWidth() - signExtendExpr.Expr.GetWidth()}{{" + $"{emitExpr(signExtendExpr.Expr)}[{signExtendExpr.Expr.GetWidth() - 1}]" + "}}, " + $"{emitExpr(signExtendExpr.Expr)}" + "}";
				return s;
			}
		}
		else if(expr is ZeroExtendExpr zeroExtendExpr)
		{
			if(zeroExtendExpr.GetWidth() - zeroExtendExpr.Expr.GetWidth() == 0)
				return emitExpr(zeroExtendExpr.Expr);
			else
			{
				string s = "{{" + $"{zeroExtendExpr.GetWidth() - zeroExtendExpr.Expr.GetWidth()}" + "{1'b0}}, " + $"{emitExpr(zeroExtendExpr.Expr)}}}";
				return s;
			}
		}
		else if(expr is ConstExpr constExpr)
		{
			ulong masked;
			if(constExpr.Width != 64)
			{
				masked = constExpr.Value & ((1UL << (int)constExpr.Width) - 1);
			}
			else if(constExpr.Width == 64)
				masked = constExpr.Value;
			else
				throw new WidthMismatchException();
			string s = $"{constExpr.Width}'d{masked}";
			return s;
		}
		else
		{
			throw new Exception();
		}
	}

	public static HashSet<Signal> CollectRegOuts(List<Stmt> stmts, HashSet<Signal> regOuts)
	{
		foreach(var item in  stmts)
		{
			if(item is SeqBlockStmt seq)
			{
				foreach(var body in seq.Body)
				{
					if(body is SeqAssignStmt sa)
						regOuts.Add(sa.Signal);
				}
			}
			if(item is MemStmt memStmt)
			{
				regOuts.Add(memStmt.Rdata);
			}
			if(item is MemWstrbStmt memWstrbStmt)
			{
				regOuts.Add(memWstrbStmt.Rdata);
			}
			if(item is IfStmt ifStmt)
			{
				foreach(var thenItem in ifStmt.Then)
				{
					if(thenItem is AssignStmt assignStmt)
						regOuts.Add(assignStmt.Signal);
				}
				if(ifStmt.Else != null)
				{
					foreach(var elseItem in ifStmt.Else)
					{
						if(elseItem is AssignStmt assignStmt)
							regOuts.Add(assignStmt.Signal);
					}
				}
			}
		}
		return regOuts;
	}

	public static void WireDefine(List<Signal> signals, StringBuilder verilogsb, HashSet<Signal> regOuts)
	{
		for(int i = 0; i < signals.Count; i++)
		{
			var item = signals[i];
			if(item.Width == 1)
			{
				if(item.Direction == SignalDirection.Input)
					verilogsb.Append($"\tinput wire {item.Name}");
				else if(regOuts.Contains(item))
					verilogsb.Append($"\toutput reg [{item.Width - 1}:0] {item.Name}");
				else if (item.Direction == SignalDirection.Output)
					verilogsb.Append($"\toutput wire {item.Name}");
			}
			else if(item.Direction == SignalDirection.Input)
				verilogsb.Append($"\tinput wire [{item.Width - 1}:0] {item.Name}");
			else if(regOuts.Contains(item))
				verilogsb.Append($"\toutput reg [{item.Width - 1}:0] {item.Name}");
			else if (item.Direction == SignalDirection.Output)
				verilogsb.Append($"\toutput wire [{item.Width - 1}:0] {item.Name}");
			if (i + 1 != signals.Count)
				verilogsb.Append(",\n");
			else
				verilogsb.Append("\n");
		}
		verilogsb.Append(");\n");
	}

	public static void EmitModuleBody(List<Stmt> stmts, StringBuilder verilogsb)
	{
		foreach(var item in stmts)
		{
			if(item is MemStmt)
			{
				verilogsb.Append($"reg [{((MemStmt)item).Width - 1}:0] mem [0:{((MemStmt)item).Depth - 1}];\n");
				verilogsb.Append($"always @(posedge {((MemStmt)item).Clk.Name}) begin\n");
				verilogsb.Append($"\tif ({((MemStmt)item).We.Name}) mem[{((MemStmt)item).Addr.Name}] <= {((MemStmt)item).Wdata.Name};\n");
				verilogsb.Append($"\t{((MemStmt)item).Rdata.Name} <= mem[{((MemStmt)item).Addr.Name}];\n");
				verilogsb.Append($"end\n");
			}
			if (item is Mem2R1WStmt mem2R1WStmt)
			{
				verilogsb.Append($"reg [{mem2R1WStmt.Width - 1}:0] mem [0:{mem2R1WStmt.Depth - 1}];\n");
				verilogsb.Append($"always @(posedge {mem2R1WStmt.Clk.Name}) begin\n");
				verilogsb.Append($"\tif ({mem2R1WStmt.We.Name}) mem[{mem2R1WStmt.Waddr.Name}] <= {mem2R1WStmt.Wdata.Name};\n");
				verilogsb.Append($"end\n");
				verilogsb.Append($"assign {mem2R1WStmt.Rdata0.Name} = mem[{mem2R1WStmt.Raddr0.Name}];\n");
				verilogsb.Append($"assign {mem2R1WStmt.Rdata1.Name} = mem[{mem2R1WStmt.Raddr1.Name}];\n");
			}
			if(item is MemWstrbStmt memWstrbStmt)
			{
				verilogsb.Append($"reg [{memWstrbStmt.Width - 1}:0] mem [0:{memWstrbStmt.Depth - 1}];\n");
				verilogsb.Append($"always @(posedge {memWstrbStmt.Clk.Name}) begin\n");
				verilogsb.Append($"\tif ({memWstrbStmt.We.Name}) begin\n");
				uint memLSB = 0;
				uint memMSB = 7;
				for(int i = 0; i < memWstrbStmt.Width / 8; i++)
				{
					verilogsb.Append($"\t\tif ({memWstrbStmt.Wstrb.Name}[{i}]) mem[{memWstrbStmt.Addr.Name}][{memMSB}:{memLSB}] <= {memWstrbStmt.Wdata.Name}[{memMSB}:{memLSB}];\n");
					memLSB += 8;
					memMSB += 8;
				}
				verilogsb.Append("\tend\n");
				verilogsb.Append($"\t{memWstrbStmt.Rdata.Name} <= mem[{memWstrbStmt.Addr.Name}];\n");
				verilogsb.Append($"end\n");
			}
			if(item is AssignStmt)
			{
				AssignStmt assignStmt = (AssignStmt)item;
				Expr expr = assignStmt.Expr;
				string s = emitExpr(expr);
				verilogsb.Append($"\tassign {assignStmt.Signal.Name} = {s};\n");
			}
			if(item is SeqBlockStmt)
			{
				SeqBlockStmt seqBlock = (SeqBlockStmt)item;
				verilogsb.Append($"\talways @(posedge {seqBlock.Clk.Name}) begin\n");
				foreach(var bodyItem in seqBlock.Body)
				{
					if(bodyItem is SeqAssignStmt seqAssign)
					{
						verilogsb.Append($"\t\tif ({seqBlock.Reset.Name}) begin\n");
						verilogsb.Append($"\t\t\t{seqAssign.Signal.Name} <= {seqAssign.Signal.Width}'d{seqAssign.ResetValue};\n");
						verilogsb.Append($"\t\tend else begin\n");
						verilogsb.Append($"\t\t\t{seqAssign.Signal.Name} <= {emitExpr(seqAssign.Expr)};\n");
						verilogsb.Append($"\t\tend\n");
					}
				}
				verilogsb.Append("\tend\n");
			}
			if(item is SwitchStmt)
			{
				SwitchStmt switchStmt = (SwitchStmt)item;
				Signal? beforeSignal = null;
				AssignStmt assignStmt;
				if(switchStmt.Cases.Count == 0)
					throw new Exception("Switch emit: Cases must not be empty.");
				for(int i = 0; i < switchStmt.Cases.Count; i++)
				{
					if(switchStmt.Cases[i].Stmts.Count != 1)
						throw new Exception($"Switch emit: case {i} (value {switchStmt.Cases[i].Value}) must contain exactly one statement, got {switchStmt.Cases[i].Stmts.Count}.");
					if(switchStmt.Cases[i].Stmts[0] is not AssignStmt)
						throw new Exception($"Switch emit: case {i} (value {switchStmt.Cases[i].Value}) must be a single AssignStmt.");
					assignStmt = (AssignStmt)switchStmt.Cases[i].Stmts[0];
					if (i != 0 && beforeSignal != assignStmt.Signal)
						throw new Exception($"Switch emit: all cases must assign the same signal (case 0: {beforeSignal!.Name}, case {i}: {assignStmt.Signal.Name}).");
					else if (i == 0)
					{
						verilogsb.Append($"\tassign {assignStmt.Signal.Name} = ({switchStmt.Signal.Name} == {switchStmt.Signal.Width}'d{switchStmt.Cases[0].Value}) ? ({emitExpr(assignStmt.Expr)}) :\n");
						beforeSignal = assignStmt.Signal;
						continue;
					}
					else if (i == switchStmt.Cases.Count - 1)
					{
						verilogsb.Append($"\t\t({emitExpr(assignStmt.Expr)});\n");
						break;
					}
					verilogsb.Append($"\t\t({switchStmt.Signal.Name} == {switchStmt.Signal.Width}'d{switchStmt.Cases[i].Value}) ? ({emitExpr(assignStmt.Expr)}) :\n");
					beforeSignal = assignStmt.Signal;
				}
			}
			if(item is IfStmt ifStmt) 
			{
				verilogsb.Append("always @(*) begin\n");
				verilogsb.Append($"\tif ({emitExpr(ifStmt.Cond)}) begin\n");
				foreach (var thenItem in ifStmt.Then)
				{
					if(thenItem is AssignStmt assignStmt)
					{
						verilogsb.Append($"\t\t{assignStmt.Signal.Name} = {emitExpr(assignStmt.Expr)};\n");
					}
					else
						throw new NotSupportedException();
				}
				verilogsb.Append("\tend\n");
				if(ifStmt.Else != null)
				{
					verilogsb.Append("\telse begin\n");
					foreach (var elseItem in ifStmt.Else)
					{
						if(elseItem is AssignStmt assignStmt)
						{
							verilogsb.Append($"\t\t{assignStmt.Signal.Name} = {emitExpr(assignStmt.Expr)};\n");
						}
						else
							throw new NotSupportedException();
					}
					verilogsb.Append("\tend\n");
				}

				verilogsb.Append("end\n");
			}
		}
	}

	public static void CollectInstances(List<Stmt> stmts, List<InstanceStmt> instanceStmts, StringBuilder verilogsb)
	{
		HashSet<string> emitted = new();
		foreach(var item in stmts)
		{
			if(item is InstanceStmt)
			{
				instanceStmts.Add((InstanceStmt)item);
				if (!emitted.Add(((InstanceStmt)item).ChildModule.GetType().Name))
					continue;
				verilogsb.Append(EmitOneModule(((InstanceStmt)item).ChildModule, ((InstanceStmt)item).ChildModule.GetType().Name, [], false));
			}
		}
	}

	public static void EmitInstanceLines(List<InstanceStmt> instanceStmts, StringBuilder verilogsb)
	{
		foreach(var item in instanceStmts)
		{
			verilogsb.Append($"\t{item.ChildModule.GetType().Name} {item.InstanceName} (\n");
			for(int i = 0; i < item.PortConnections.Count; i++)
			{
				if(i == item.PortConnections.Count - 1)
					verilogsb.Append($"\t\t.{item.PortConnections[i].ChildPort.Name}({item.PortConnections[i].ParentSignal.Name})");
				else
					verilogsb.Append($"\t\t.{item.PortConnections[i].ChildPort.Name}({item.PortConnections[i].ParentSignal.Name}),");
			}
			verilogsb.Append(");\n");
		}
	}

	public static string EmitOneModule(Module module, string moduleName, List<InstanceStmt> instanceStmts, bool emitHierarchy)
	{
		StringBuilder verilogsb = new();

		List<Signal> signals = module.GetPorts().ToList();
		List<Stmt> stmts = module.GetStmts().ToList(); 
		HashSet<Signal> regOuts = new();

		if(emitHierarchy)
		{
			CollectInstances(stmts, instanceStmts, verilogsb);
		}

		verilogsb.Append($"module {moduleName}(\n");
		CollectRegOuts(stmts, regOuts);
		
		WireDefine(signals, verilogsb, regOuts);

		if(emitHierarchy)
		{
			EmitInstanceLines(instanceStmts, verilogsb);
		}
		
		EmitModuleBody(stmts, verilogsb);

		verilogsb.Append("endmodule");

		return verilogsb.ToString();
	}
}
