namespace SharpHdl.Emit;

/// <summary>
/// Verilog emitter の入口プレースホルダ。実装は docs/verilog-emit-spec.md に従う。
/// </summary>
public static class VerilogEmitter
{
    public static string EmitPlaceholder(string moduleName) =>
        $"// Generated by CsharpHdl (stub)\nmodule {moduleName};\nendmodule\n";
}
