using System.Text;
using SharpHdl.Core.Model;

namespace SharpHdl.Emit;

/// <summary>
/// Verilog emitter の入口プレースホルダ。実装は docs/verilog-emit-spec.md に従う。
/// </summary>
public static class VerilogEmitter
{
    public static string EmitPlaceholder(string moduleName) =>
        $"// Generated by CsharpHdl (stub)\nmodule {moduleName};\nendmodule\n";

	public static string Emitter(Module top, string topName)
	{
		StringBuilder verilogsb = new();

		List<Signal> signals = top.GetPorts().ToList();
		List<Stmt> stmts = top.GetStmts().ToList();
		List<InstanceStmt> instanceStmts = new();
		HashSet<string> emitted = new();
		HashSet<Signal> regOuts = new();

		foreach(var item in  stmts)
		{
			if(item is InstanceStmt)
			{
				instanceStmts.Add((InstanceStmt)item);
				if (!emitted.Add(((InstanceStmt)item).ChildModule.GetType().Name))
        			continue;
				verilogsb.Append(SingleModuleEmitter(((InstanceStmt)item).ChildModule, ((InstanceStmt)item).ChildModule.GetType().Name));
			}
			if(item is SeqBlockStmt seq)
			{
				foreach(var body in seq.Body)
				{
					if(body is SeqAssignStmt sa)
						regOuts.Add(sa.Signal);
				}
			}
			if(item is MemStmt mem)
			{
				regOuts.Add(mem.Rdata);
			}
		}

		verilogsb.Append($"module {topName}(\n");
		for(int i = 0; i < signals.Count; i++)
		{
			var item = signals[i];
			if(item.Width == 1)
			{
				if(item.Direction == SignalDirection.Input)
					verilogsb.Append($"\tinput wire {item.Name}");
				else if(regOuts.Contains(item))
					verilogsb.Append($"\toutput reg [{item.Width - 1}:0] {item.Name}");
				else if (item.Direction == SignalDirection.Output)
					verilogsb.Append($"\toutput wire {item.Name}");
			}
			else if(item.Direction == SignalDirection.Input)
				verilogsb.Append($"\tinput wire [{item.Width - 1}:0] {item.Name}");
			else if(regOuts.Contains(item))
				verilogsb.Append($"\toutput reg [{item.Width - 1}:0] {item.Name}");
			else if (item.Direction == SignalDirection.Output)
				verilogsb.Append($"\toutput wire [{item.Width - 1}:0] {item.Name}");
			if (i + 1 != signals.Count)
				verilogsb.Append(",\n");
			else
				verilogsb.Append("\n");
		}
		verilogsb.Append(");\n");

		foreach(var item in instanceStmts)
		{
			verilogsb.Append($"\t{item.ChildModule.GetType().Name} {item.InstanceName} (\n");
			for(int i = 0; i < item.PortConnections.Count; i++)
			{
				if(i == item.PortConnections.Count - 1)
					verilogsb.Append($"\t\t.{item.PortConnections[i].ChildPort.Name}({item.PortConnections[i].ParentSignal.Name})");
				else
					verilogsb.Append($"\t\t.{item.PortConnections[i].ChildPort.Name}({item.PortConnections[i].ParentSignal.Name}),");
			}
			verilogsb.Append(");\n");
		}

		foreach(var item in stmts)
		{
			if(item is MemStmt)
			{
				verilogsb.Append($"reg [{((MemStmt)item).Width - 1}:0] mem [0:{((MemStmt)item).Depth - 1}];\n");
				verilogsb.Append($"always @(posedge {((MemStmt)item).Clk.Name}) begin\n");
				verilogsb.Append($"\tif ({((MemStmt)item).We.Name}) mem[{((MemStmt)item).Addr.Name}] <= {((MemStmt)item).Wdata.Name};\n");
				verilogsb.Append($"\t{((MemStmt)item).Rdata.Name} <= mem[{((MemStmt)item).Addr.Name}];\n");
				verilogsb.Append($"end\n");
			}
			if(item is AssignStmt)
			{
				AssignStmt assignStmt = (AssignStmt)item;
				Expr expr = assignStmt.Expr;
				string s = emitExpr(expr);
				verilogsb.Append($"\tassign {assignStmt.Signal.Name} = {s};\n");
			}
			if(item is SeqBlockStmt)
			{
				SeqBlockStmt seqBlock = (SeqBlockStmt)item;
				verilogsb.Append($"\talways @(posedge {seqBlock.Clk.Name}) begin\n");
				foreach(var bodyItem in seqBlock.Body)
				{
					if(bodyItem is SeqAssignStmt seqAssign)
					{
						verilogsb.Append($"\t\tif ({seqBlock.Reset.Name}) begin\n");
						verilogsb.Append($"\t\t\t{seqAssign.Signal.Name} <= {seqAssign.Signal.Width}'d{seqAssign.ResetValue};\n");
						verilogsb.Append($"\t\tend else begin\n");
						verilogsb.Append($"\t\t\t{seqAssign.Signal.Name} <= {emitExpr(seqAssign.Expr)};\n");
						verilogsb.Append($"\t\tend\n");
					}
				}
				verilogsb.Append("\tend\n");
			}
			if(item is SwitchStmt)
			{
				SwitchStmt switchStmt = (SwitchStmt)item;
				Signal? beforeSignal = null;
				AssignStmt assignStmt = assignStmt = (AssignStmt)switchStmt.Cases[0].Stmts[0];
				for(int i = 0; i < switchStmt.Cases.Count; i++)
				{
					assignStmt = (AssignStmt)switchStmt.Cases[i].Stmts[0];
					if (i != 0 && beforeSignal != assignStmt.Signal)
						throw new Exception();
					else if (i == 0)
					{
						verilogsb.Append($"\tassign {assignStmt.Signal.Name} = ({switchStmt.Signal.Name} == {switchStmt.Signal.Width}'d{switchStmt.Cases[0].Value}) ? ({emitExpr(assignStmt.Expr)}) :\n");
						beforeSignal = assignStmt.Signal;
						continue;
					}
					else if (i == switchStmt.Cases.Count - 1)
					{
						verilogsb.Append($"\t\t({emitExpr(assignStmt.Expr)});\n");
						break;
					}
					verilogsb.Append($"\t\t({switchStmt.Signal.Name} == {switchStmt.Signal.Width}'d{switchStmt.Cases[i].Value}) ? ({emitExpr(assignStmt.Expr)}) :\n");
					beforeSignal = assignStmt.Signal;
				}
			}
		}

		verilogsb.Append("endmodule");


		return verilogsb.ToString();
	}

	public static string SingleModuleEmitter(Module module, string moduleName)
	{
		StringBuilder verilogsb = new();

		List<Signal> signals = module.GetPorts().ToList();
		List<Stmt> stmts = module.GetStmts().ToList(); 
		HashSet<Signal> regOuts = new();
		
		verilogsb.Append($"module {moduleName}(\n");
		foreach(var item in  stmts)
		{
			if(item is SeqBlockStmt seq)
			{
				foreach(var body in seq.Body)
				{
					if(body is SeqAssignStmt sa)
						regOuts.Add(sa.Signal);
				}
			}
			if(item is MemStmt mem)
			{
				regOuts.Add(mem.Rdata);
			}
		}
		for(int i = 0; i < signals.Count; i++)
		{
			var item = signals[i];
			if(item.Width == 1)
			{
				if(item.Direction == SignalDirection.Input)
					verilogsb.Append($"\tinput wire {item.Name}");
				else if(regOuts.Contains(item))
					verilogsb.Append($"\toutput reg [{item.Width - 1}:0] {item.Name}");
				else if (item.Direction == SignalDirection.Output)
					verilogsb.Append($"\toutput wire {item.Name}");
			}
			else if(item.Direction == SignalDirection.Input)
				verilogsb.Append($"\tinput wire [{item.Width - 1}:0] {item.Name}");
			else if(regOuts.Contains(item))
				verilogsb.Append($"\toutput reg [{item.Width - 1}:0] {item.Name}");
			else if (item.Direction == SignalDirection.Output)
				verilogsb.Append($"\toutput wire [{item.Width - 1}:0] {item.Name}");
			if (i + 1 != signals.Count)
				verilogsb.Append(",\n");
			else
				verilogsb.Append("\n");
		}
		verilogsb.Append(");\n");
		foreach(var item in stmts)
		{
			if(item is MemStmt)
			{
				verilogsb.Append($"reg [{((MemStmt)item).Width - 1}:0] mem [0:{((MemStmt)item).Depth - 1}];\n");
				verilogsb.Append($"always @(posedge {((MemStmt)item).Clk.Name}) begin\n");
				verilogsb.Append($"\tif ({((MemStmt)item).We.Name}) mem[{((MemStmt)item).Addr.Name}] <= {((MemStmt)item).Wdata.Name};\n");
				verilogsb.Append($"\t{((MemStmt)item).Rdata.Name} <= mem[{((MemStmt)item).Addr.Name}];\n");
				verilogsb.Append($"end\n");
			}
			if(item is AssignStmt)
			{
				AssignStmt assignStmt = (AssignStmt)item;
				Expr expr = assignStmt.Expr;
				string s = emitExpr(expr);
				verilogsb.Append($"\tassign {assignStmt.Signal.Name} = {s};\n");
			}
			if(item is SeqBlockStmt)
			{
				SeqBlockStmt seqBlock = (SeqBlockStmt)item;
				verilogsb.Append($"\talways @(posedge {seqBlock.Clk.Name}) begin\n");
				foreach(var bodyItem in seqBlock.Body)
				{
					if(bodyItem is SeqAssignStmt seqAssign)
					{
						verilogsb.Append($"\t\tif ({seqBlock.Reset.Name}) begin\n");
						verilogsb.Append($"\t\t\t{seqAssign.Signal.Name} <= {seqAssign.Signal.Width}'d{seqAssign.ResetValue};\n");
						verilogsb.Append($"\t\tend else begin\n");
						verilogsb.Append($"\t\t\t{seqAssign.Signal.Name} <= {emitExpr(seqAssign.Expr)};\n");
						verilogsb.Append($"\t\tend\n");
					}
				}
				verilogsb.Append("\tend\n");
			}
			if(item is SwitchStmt)
			{
				SwitchStmt switchStmt = (SwitchStmt)item;
				Signal? beforeSignal = null;
				AssignStmt assignStmt = assignStmt = (AssignStmt)switchStmt.Cases[0].Stmts[0];
				for(int i = 0; i < switchStmt.Cases.Count; i++)
				{
					assignStmt = (AssignStmt)switchStmt.Cases[i].Stmts[0];
					if (i != 0 && beforeSignal != assignStmt.Signal)
						throw new Exception();
					else if (i == 0)
					{
						verilogsb.Append($"\tassign {assignStmt.Signal.Name} = ({switchStmt.Signal.Name} == {switchStmt.Signal.Width}'d{switchStmt.Cases[0].Value}) ? ({emitExpr(assignStmt.Expr)}) :\n");
						beforeSignal = assignStmt.Signal;
						continue;
					}
					else if (i == switchStmt.Cases.Count - 1)
					{
						verilogsb.Append($"\t\t({emitExpr(assignStmt.Expr)});\n");
						break;
					}
					verilogsb.Append($"\t\t({switchStmt.Signal.Name} == {switchStmt.Signal.Width}'d{switchStmt.Cases[i].Value}) ? ({emitExpr(assignStmt.Expr)}) :\n");
					beforeSignal = assignStmt.Signal;
				}
			}
		}
		verilogsb.Append("endmodule");

		return verilogsb.ToString();
	}

	public static string emitExpr(Expr expr)
	{
		
		if(expr is Signal)
		{
			Signal signal = (Signal)expr;
			return signal.Name;
		}
		else if(expr is OpExpr)
		{
			OpExpr opExpr = (OpExpr)expr;
			return emitExpr(opExpr.Left) + " " + opExpr.Op.ToCustomString() + " " + emitExpr(opExpr.Right);
		}
		else if(expr is SliceExpr sliceExpr)
		{
			return emitExpr(sliceExpr.Expr) + $"[{sliceExpr.MSB}:{sliceExpr.LSB}]";
		}
		else
		{
			throw new Exception();
		}
	}
}
